### PR TITLE
Assertions and Silencing Output

### PR DESCRIPTION
**Pull request by ejmr**
I've found your `log.lua` to be very useful and easy to integrate into a project I'm currently working on.  These patches implement two simple features which I needed for that project, but which you and others may find useful as well:
1. If the `log.silent` property is true then the logging functions will produce no output.  There are times I want to disable all log output, similar to using `NDEBUG` in C to silence `assert()`.
2. The `log.assert()` function is similar to Lua's standard `assert()`, but it accepts an optional third argument which must be the name of one of the logging levels.  This makes it possible to write code such as:

``` lua
log.assert(x == y, "X is not equal to Y", "warn")
```

This code is (nearly) equivalent to:

``` lua
if not x == y then
    log.warn("X is not equal to Y")
end
```

The slight difference between the two examples is that `log.assert()` returns the value of its first parameter, just like Lua's standard `assert()`.

### CODE REVIEW

**Comment by rxi** [comment]
Thanks for the contribution. A few small changes before I'd be happy merging:
- The indentation is inconsistent with the existing style in a couple of places (`83 - 85`, `105`), and the example in the README
- Defaulting to the current `log.level` on the assertion doesn't seem like a logical default. `"warn"` `"error"` or `"fatal"` feels like it would be more of a sane default or perhaps no default at all?
- I'm unsure about the use of the field `silent` to disable logging completely -- it feels as if it would be more appropriate to set the `log.level` to `"error"` or `"fatal"` such that most the logs are disabled but the events being logged which would cause the program to fail would still be outputted. I can't think of a situation where you would want to suppress the `"fatal"` messages.
- Can you change your copyright line to something to the effect of "With portions copyright..." so that the original author is clear?

Thanks

**Comment by ejmr** [comment]
> Defaulting to the current log.level on the assertion doesn't seem like a logical default. "warn" "error" or "fatal" feels like it would be more of a sane default or perhaps no default at all?

The reason I wanted a default is so that I could easily make wide-spread replacements of `assert(...)` with `log.assert(...)` through-out a large code-base without having to add a third parameter everytime.  However, I wasn't sure what would be the best default.  Using `log.level` felt like a simple albeit arbitrary decision.  I can't honestly disagree with your suggestion though.  For my own code I would lean towards `"warn"` or `"error"`.  Since the standard `assert()` can bring programs to a halt one of the stronger levels seems most appropriate---maybe `"error"` then?

> I'm unsure about the use of the field silent to disable logging completely... I can't think of a situation where you would want to suppress the "fatal" messages.

I added that on/off switch because I'm using the library on a game and I don't want the "release" version to create any kind of log, as I see it as "unwanted noise" on the player's end.  That said, I don't feel particularly strongly about it either.  I wouldn't disagree if you thought the flag was too extreme.

> Can you change your copyright line to something to the effect of "With portions copyright..." so that the original author is clear?

Certainly.  I'll reword things to make very clear the original authorship.  And will make the indentation consistent as well.

**Comment by ejmr** [comment]
After thinking it over for a day, I changed `log.assert()` to default to `"error"`, because I've come to agree with you that `log.level` is not a good choice for the default.

**Comment by rxi** [comment]
> I added that on/off switch because I'm using the library on a game and I don't want the "release" version to create any kind of log, as I see it as "unwanted noise" on the player's end.

`log.level` exists for this same purpose. The idea is that you would use a low level during development, then set it to something like `fatal` (or `error`) on release. By definition the program shouldn't be recoverable from a fatal error, thus the only thing ever outputted on the log would be information about the error before the program presumably aborts. Given `log.level` exists I think the `silent` field just duplicates functionality without really adding value.

The formatting changes look good.

I had some thoughts on `log.assert()` since my initial comment: 

I'm not sure whether or not the naming of the `assert()` function implies that if the assertion fails an error will be thrown -- this is the case with Lua's assert and other `assert` functions. Should the `log` module be in charge of throwing these error? I don't think it's the job of the `log` module to do this. Additionally, if the assertion fails and the error is logged (with a default of `error`) isn't it implied the error should also be handled in some way? If the error is to be handled it means the condition would have to be checked again anyway, making the use of the function redundant.

Perhaps a better option would be renaming the function to `log.check()` with a default level of `warn` or `debug`. This avoids the connotations the name `assert` might hold, and the `warn` (or below) level makes a bit more sense regarding conditions which don't necessarily have to be handled specially.

**Comment by ejmr** [comment]
>  Should the `log` module be in charge of throwing these error? I don't think it's the job of the `log` module to do this.

I agree.

> Additionally, if the assertion fails and the error is logged (with a default of `error`) isn't it implied the error should also be handled in some way?

Yes, I agree with as well.  However, one reason I wrote `log.assert()` in a such that I could use it to replace my uses of Lua's `assert()` is because it is tedious for debugging to see my game crash on the first assertion; I want the game to run as long as it can before it comes to a complete halt since restarting it after any blue-screen in LÖVE becomes a time-sink.  I'm not advocating that as a sound practice---in truth I "know better"---but it's convenient to me.  As is `silent`, but I think it makes sense to remove that.

I like your idea re. `log.check()`.  The way `log.assert()` works right now is convenient to me but as I've thought about it I have come to the same conclusion that many developers would expect `log.assert()` to bring the program to a stop the way `assert()` does; the name would likely given developers the wrong expectation about its behavior.  Replacing it with `log.check()` sounds like a good idea to me.

**Comment by ejmr** [comment]
I closed this because I'm going to open a pull-request with the changes and omissions we've discussed here.

**Pull request closed without merging**
